// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YonetIQ.Data;

#nullable disable

namespace YonetIQ.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311114916_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YonetIQ.Data.Models.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Atanan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("AtananKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AtanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Oncelik")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AtananKullaniciId");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("YonetIQ.Data.Models.Karar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BagliGorevId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("GoreveDonustuMu")
                        .HasColumnType("bit");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Sorumlu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SorumluKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("ToplantiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BagliGorevId");

                    b.HasIndex("SorumluKullaniciId");

                    b.HasIndex("ToplantiId");

                    b.ToTable("Kararlar");
                });

            modelBuilder.Entity("YonetIQ.Data.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Eposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("YonetIQ.Data.Models.RaporFavori", b =>
                {
                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("SorguId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("KullaniciId", "SorguId");

                    b.HasIndex("SorguId");

                    b.ToTable("RaporFavoriler");
                });

            modelBuilder.Entity("YonetIQ.Data.Models.SetiSorgu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GenislikMd")
                        .HasColumnType("int");

                    b.Property<int>("SetiId")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<int>("SorguId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SetiId");

                    b.HasIndex("SorguId");

                    b.ToTable("SetiSorgular");
                });

            modelBuilder.Entity("YonetIQ.Data.Models.QueryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("GuncellenmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullanimAmaci")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PivotDegerKolon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PivotSatirKolon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PivotSutunKolon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Renk")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SonucTipi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Sql")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("Id");

                    b.ToTable("QueryRecordlar");
                });

            modelBuilder.Entity("YonetIQ.Data.Models.SorguSeti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ikon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("NavMenuGoster")
                        .HasColumnType("bit");

                    b.Property<int>("NavMenuSira")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("SorguSetleri");
                });

            modelBuilder.Entity("YonetIQ.Data.Models.Toplanti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gundem")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Katilimcilar")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Notlar")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToplantiLinki")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Yer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Toplantilar");
                });

            modelBuilder.Entity("YonetIQ.Data.Models.Gorev", b =>
                {
                    b.HasOne("YonetIQ.Data.Models.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("AtananKullaniciId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("YonetIQ.Data.Models.Karar", b =>
                {
                    b.HasOne("YonetIQ.Data.Models.Gorev", null)
                        .WithMany()
                        .HasForeignKey("BagliGorevId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YonetIQ.Data.Models.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("SorumluKullaniciId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YonetIQ.Data.Models.Toplanti", null)
                        .WithMany("Kararlar")
                        .HasForeignKey("ToplantiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YonetIQ.Data.Models.RaporFavori", b =>
                {
                    b.HasOne("YonetIQ.Data.Models.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YonetIQ.Data.Models.QueryRecord", null)
                        .WithMany()
                        .HasForeignKey("SorguId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YonetIQ.Data.Models.SetiSorgu", b =>
                {
                    b.HasOne("YonetIQ.Data.Models.SorguSeti", null)
                        .WithMany()
                        .HasForeignKey("SetiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YonetIQ.Data.Models.QueryRecord", null)
                        .WithMany()
                        .HasForeignKey("SorguId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YonetIQ.Data.Models.Toplanti", b =>
                {
                    b.Navigation("Kararlar");
                });
#pragma warning restore 612, 618
        }
    }
}
